server:
  servlet:
    context-path: /luckyMoney
  port: 8080


  #配置数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?serverTimezone=GMT
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
